apiVersion: v1
kind: Service
metadata:
  name: kotlin-test-app
spec:
  selector:
    app: kotlin-test-app
  ports:
    - protocol: TCP
      port: 80 # this port is used by the ingress to access the service
      targetPort: 9090 # this port matches the containerPort defined in the deployment