name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten sha
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA:0:6}" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jacekgdev11/kotlin-test-app:${{ env.sha_short }}
    outputs:
      commit_id: ${{ env.sha_short }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Modify values.yaml
        shell: bash
        env:
          commit_id: ${{ needs.ci.outputs.commit_id }}
        run: |
          echo "commit_id=${{ needs.ci.outputs.commit_id }}"
          sudo apt update
          sudo apt install yq -y
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/kotlin-test-app/values.yaml
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'Uptate values.yaml image tag to ${{ needs.ci.outputs.commit_id }}'
          add: 'report.txt'
      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync kotlin-test-app